// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/kontekst.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_kontekst_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Bind               string                 `protobuf:"bytes,1,opt,name=bind,proto3" json:"bind,omitempty"`
	Endpoint           string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ModelDir           string                 `protobuf:"bytes,4,opt,name=model_dir,json=modelDir,proto3" json:"model_dir,omitempty"`
	LlamaServerHealthy bool                   `protobuf:"varint,6,opt,name=llama_server_healthy,json=llamaServerHealthy,proto3" json:"llama_server_healthy,omitempty"`
	LlamaServerRunning bool                   `protobuf:"varint,7,opt,name=llama_server_running,json=llamaServerRunning,proto3" json:"llama_server_running,omitempty"`
	LlamaServerPid     int32                  `protobuf:"varint,8,opt,name=llama_server_pid,json=llamaServerPid,proto3" json:"llama_server_pid,omitempty"`
	UptimeSeconds      int64                  `protobuf:"varint,9,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	StartedAtRfc3339   string                 `protobuf:"bytes,10,opt,name=started_at_rfc3339,json=startedAtRfc3339,proto3" json:"started_at_rfc3339,omitempty"`
	DataDir            string                 `protobuf:"bytes,11,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_kontekst_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetBind() string {
	if x != nil {
		return x.Bind
	}
	return ""
}

func (x *GetStatusResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *GetStatusResponse) GetModelDir() string {
	if x != nil {
		return x.ModelDir
	}
	return ""
}

func (x *GetStatusResponse) GetLlamaServerHealthy() bool {
	if x != nil {
		return x.LlamaServerHealthy
	}
	return false
}

func (x *GetStatusResponse) GetLlamaServerRunning() bool {
	if x != nil {
		return x.LlamaServerRunning
	}
	return false
}

func (x *GetStatusResponse) GetLlamaServerPid() int32 {
	if x != nil {
		return x.LlamaServerPid
	}
	return 0
}

func (x *GetStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetStartedAtRfc3339() string {
	if x != nil {
		return x.StartedAtRfc3339
	}
	return ""
}

func (x *GetStatusResponse) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_kontekst_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{2}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_kontekst_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{3}
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RunCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*RunCommand_Start
	//	*RunCommand_ApproveTool
	//	*RunCommand_DenyTool
	//	*RunCommand_ApproveAll
	//	*RunCommand_DenyAll
	//	*RunCommand_Cancel
	Command       isRunCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommand) Reset() {
	*x = RunCommand{}
	mi := &file_proto_kontekst_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommand) ProtoMessage() {}

func (x *RunCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommand.ProtoReflect.Descriptor instead.
func (*RunCommand) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{4}
}

func (x *RunCommand) GetCommand() isRunCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RunCommand) GetStart() *StartRunCommand {
	if x != nil {
		if x, ok := x.Command.(*RunCommand_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *RunCommand) GetApproveTool() *ApproveToolCommand {
	if x != nil {
		if x, ok := x.Command.(*RunCommand_ApproveTool); ok {
			return x.ApproveTool
		}
	}
	return nil
}

func (x *RunCommand) GetDenyTool() *DenyToolCommand {
	if x != nil {
		if x, ok := x.Command.(*RunCommand_DenyTool); ok {
			return x.DenyTool
		}
	}
	return nil
}

func (x *RunCommand) GetApproveAll() *ApproveAllToolsCommand {
	if x != nil {
		if x, ok := x.Command.(*RunCommand_ApproveAll); ok {
			return x.ApproveAll
		}
	}
	return nil
}

func (x *RunCommand) GetDenyAll() *DenyAllToolsCommand {
	if x != nil {
		if x, ok := x.Command.(*RunCommand_DenyAll); ok {
			return x.DenyAll
		}
	}
	return nil
}

func (x *RunCommand) GetCancel() *CancelRunCommand {
	if x != nil {
		if x, ok := x.Command.(*RunCommand_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isRunCommand_Command interface {
	isRunCommand_Command()
}

type RunCommand_Start struct {
	Start *StartRunCommand `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type RunCommand_ApproveTool struct {
	ApproveTool *ApproveToolCommand `protobuf:"bytes,2,opt,name=approve_tool,json=approveTool,proto3,oneof"`
}

type RunCommand_DenyTool struct {
	DenyTool *DenyToolCommand `protobuf:"bytes,3,opt,name=deny_tool,json=denyTool,proto3,oneof"`
}

type RunCommand_ApproveAll struct {
	ApproveAll *ApproveAllToolsCommand `protobuf:"bytes,4,opt,name=approve_all,json=approveAll,proto3,oneof"`
}

type RunCommand_DenyAll struct {
	DenyAll *DenyAllToolsCommand `protobuf:"bytes,5,opt,name=deny_all,json=denyAll,proto3,oneof"`
}

type RunCommand_Cancel struct {
	Cancel *CancelRunCommand `protobuf:"bytes,6,opt,name=cancel,proto3,oneof"`
}

func (*RunCommand_Start) isRunCommand_Command() {}

func (*RunCommand_ApproveTool) isRunCommand_Command() {}

func (*RunCommand_DenyTool) isRunCommand_Command() {}

func (*RunCommand_ApproveAll) isRunCommand_Command() {}

func (*RunCommand_DenyAll) isRunCommand_Command() {}

func (*RunCommand_Cancel) isRunCommand_Command() {}

type StartRunCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Skill         *SkillInvocation       `protobuf:"bytes,5,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunCommand) Reset() {
	*x = StartRunCommand{}
	mi := &file_proto_kontekst_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunCommand) ProtoMessage() {}

func (x *StartRunCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunCommand.ProtoReflect.Descriptor instead.
func (*StartRunCommand) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{5}
}

func (x *StartRunCommand) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *StartRunCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartRunCommand) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *StartRunCommand) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *StartRunCommand) GetSkill() *SkillInvocation {
	if x != nil {
		return x.Skill
	}
	return nil
}

type SkillInvocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillInvocation) Reset() {
	*x = SkillInvocation{}
	mi := &file_proto_kontekst_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillInvocation) ProtoMessage() {}

func (x *SkillInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillInvocation.ProtoReflect.Descriptor instead.
func (*SkillInvocation) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{6}
}

func (x *SkillInvocation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillInvocation) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type ApproveToolCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveToolCommand) Reset() {
	*x = ApproveToolCommand{}
	mi := &file_proto_kontekst_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveToolCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveToolCommand) ProtoMessage() {}

func (x *ApproveToolCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveToolCommand.ProtoReflect.Descriptor instead.
func (*ApproveToolCommand) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{7}
}

func (x *ApproveToolCommand) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type DenyToolCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyToolCommand) Reset() {
	*x = DenyToolCommand{}
	mi := &file_proto_kontekst_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyToolCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyToolCommand) ProtoMessage() {}

func (x *DenyToolCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyToolCommand.ProtoReflect.Descriptor instead.
func (*DenyToolCommand) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{8}
}

func (x *DenyToolCommand) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *DenyToolCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApproveAllToolsCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAllToolsCommand) Reset() {
	*x = ApproveAllToolsCommand{}
	mi := &file_proto_kontekst_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAllToolsCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAllToolsCommand) ProtoMessage() {}

func (x *ApproveAllToolsCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAllToolsCommand.ProtoReflect.Descriptor instead.
func (*ApproveAllToolsCommand) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{9}
}

func (x *ApproveAllToolsCommand) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type DenyAllToolsCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyAllToolsCommand) Reset() {
	*x = DenyAllToolsCommand{}
	mi := &file_proto_kontekst_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyAllToolsCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyAllToolsCommand) ProtoMessage() {}

func (x *DenyAllToolsCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyAllToolsCommand.ProtoReflect.Descriptor instead.
func (*DenyAllToolsCommand) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{10}
}

func (x *DenyAllToolsCommand) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *DenyAllToolsCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelRunCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunCommand) Reset() {
	*x = CancelRunCommand{}
	mi := &file_proto_kontekst_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunCommand) ProtoMessage() {}

func (x *CancelRunCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunCommand.ProtoReflect.Descriptor instead.
func (*CancelRunCommand) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{11}
}

type RunEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunEvent_Started
	//	*RunEvent_Token
	//	*RunEvent_Reasoning
	//	*RunEvent_BatchProposed
	//	*RunEvent_ToolStarted
	//	*RunEvent_ToolCompleted
	//	*RunEvent_ToolFailed
	//	*RunEvent_BatchCompleted
	//	*RunEvent_Completed
	//	*RunEvent_Cancelled
	//	*RunEvent_Failed
	Event         isRunEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{12}
}

func (x *RunEvent) GetEvent() isRunEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunEvent) GetStarted() *RunStartedEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *RunEvent) GetToken() *TokenDeltaEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *RunEvent) GetReasoning() *ReasoningDeltaEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Reasoning); ok {
			return x.Reasoning
		}
	}
	return nil
}

func (x *RunEvent) GetBatchProposed() *ToolBatchProposedEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_BatchProposed); ok {
			return x.BatchProposed
		}
	}
	return nil
}

func (x *RunEvent) GetToolStarted() *ToolExecutionStartedEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_ToolStarted); ok {
			return x.ToolStarted
		}
	}
	return nil
}

func (x *RunEvent) GetToolCompleted() *ToolExecutionCompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_ToolCompleted); ok {
			return x.ToolCompleted
		}
	}
	return nil
}

func (x *RunEvent) GetToolFailed() *ToolExecutionFailedEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_ToolFailed); ok {
			return x.ToolFailed
		}
	}
	return nil
}

func (x *RunEvent) GetBatchCompleted() *ToolBatchCompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_BatchCompleted); ok {
			return x.BatchCompleted
		}
	}
	return nil
}

func (x *RunEvent) GetCompleted() *RunCompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *RunEvent) GetCancelled() *RunCancelledEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Cancelled); ok {
			return x.Cancelled
		}
	}
	return nil
}

func (x *RunEvent) GetFailed() *RunFailedEvent {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

type isRunEvent_Event interface {
	isRunEvent_Event()
}

type RunEvent_Started struct {
	Started *RunStartedEvent `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type RunEvent_Token struct {
	Token *TokenDeltaEvent `protobuf:"bytes,2,opt,name=token,proto3,oneof"`
}

type RunEvent_Reasoning struct {
	Reasoning *ReasoningDeltaEvent `protobuf:"bytes,3,opt,name=reasoning,proto3,oneof"`
}

type RunEvent_BatchProposed struct {
	BatchProposed *ToolBatchProposedEvent `protobuf:"bytes,4,opt,name=batch_proposed,json=batchProposed,proto3,oneof"`
}

type RunEvent_ToolStarted struct {
	ToolStarted *ToolExecutionStartedEvent `protobuf:"bytes,5,opt,name=tool_started,json=toolStarted,proto3,oneof"`
}

type RunEvent_ToolCompleted struct {
	ToolCompleted *ToolExecutionCompletedEvent `protobuf:"bytes,6,opt,name=tool_completed,json=toolCompleted,proto3,oneof"`
}

type RunEvent_ToolFailed struct {
	ToolFailed *ToolExecutionFailedEvent `protobuf:"bytes,7,opt,name=tool_failed,json=toolFailed,proto3,oneof"`
}

type RunEvent_BatchCompleted struct {
	BatchCompleted *ToolBatchCompletedEvent `protobuf:"bytes,8,opt,name=batch_completed,json=batchCompleted,proto3,oneof"`
}

type RunEvent_Completed struct {
	Completed *RunCompletedEvent `protobuf:"bytes,9,opt,name=completed,proto3,oneof"`
}

type RunEvent_Cancelled struct {
	Cancelled *RunCancelledEvent `protobuf:"bytes,10,opt,name=cancelled,proto3,oneof"`
}

type RunEvent_Failed struct {
	Failed *RunFailedEvent `protobuf:"bytes,11,opt,name=failed,proto3,oneof"`
}

func (*RunEvent_Started) isRunEvent_Event() {}

func (*RunEvent_Token) isRunEvent_Event() {}

func (*RunEvent_Reasoning) isRunEvent_Event() {}

func (*RunEvent_BatchProposed) isRunEvent_Event() {}

func (*RunEvent_ToolStarted) isRunEvent_Event() {}

func (*RunEvent_ToolCompleted) isRunEvent_Event() {}

func (*RunEvent_ToolFailed) isRunEvent_Event() {}

func (*RunEvent_BatchCompleted) isRunEvent_Event() {}

func (*RunEvent_Completed) isRunEvent_Event() {}

func (*RunEvent_Cancelled) isRunEvent_Event() {}

func (*RunEvent_Failed) isRunEvent_Event() {}

type RunStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"` // Agent being used for this run
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStartedEvent) Reset() {
	*x = RunStartedEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStartedEvent) ProtoMessage() {}

func (x *RunStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStartedEvent.ProtoReflect.Descriptor instead.
func (*RunStartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{13}
}

func (x *RunStartedEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunStartedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunStartedEvent) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

type TokenDeltaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDeltaEvent) Reset() {
	*x = TokenDeltaEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDeltaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDeltaEvent) ProtoMessage() {}

func (x *TokenDeltaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDeltaEvent.ProtoReflect.Descriptor instead.
func (*TokenDeltaEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{14}
}

func (x *TokenDeltaEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ReasoningDeltaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningDeltaEvent) Reset() {
	*x = ReasoningDeltaEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningDeltaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningDeltaEvent) ProtoMessage() {}

func (x *ReasoningDeltaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningDeltaEvent.ProtoReflect.Descriptor instead.
func (*ReasoningDeltaEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{15}
}

func (x *ReasoningDeltaEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ToolBatchProposedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Calls         []*ProposedToolCall    `protobuf:"bytes,2,rep,name=calls,proto3" json:"calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolBatchProposedEvent) Reset() {
	*x = ToolBatchProposedEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolBatchProposedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolBatchProposedEvent) ProtoMessage() {}

func (x *ToolBatchProposedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolBatchProposedEvent.ProtoReflect.Descriptor instead.
func (*ToolBatchProposedEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{16}
}

func (x *ToolBatchProposedEvent) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *ToolBatchProposedEvent) GetCalls() []*ProposedToolCall {
	if x != nil {
		return x.Calls
	}
	return nil
}

type ProposedToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	Preview       string                 `protobuf:"bytes,4,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposedToolCall) Reset() {
	*x = ProposedToolCall{}
	mi := &file_proto_kontekst_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposedToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposedToolCall) ProtoMessage() {}

func (x *ProposedToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposedToolCall.ProtoReflect.Descriptor instead.
func (*ProposedToolCall) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{17}
}

func (x *ProposedToolCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ProposedToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProposedToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ProposedToolCall) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

type ToolExecutionStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionStartedEvent) Reset() {
	*x = ToolExecutionStartedEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionStartedEvent) ProtoMessage() {}

func (x *ToolExecutionStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionStartedEvent.ProtoReflect.Descriptor instead.
func (*ToolExecutionStartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{18}
}

func (x *ToolExecutionStartedEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type ToolExecutionCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionCompletedEvent) Reset() {
	*x = ToolExecutionCompletedEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionCompletedEvent) ProtoMessage() {}

func (x *ToolExecutionCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionCompletedEvent.ProtoReflect.Descriptor instead.
func (*ToolExecutionCompletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{19}
}

func (x *ToolExecutionCompletedEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolExecutionCompletedEvent) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ToolExecutionFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolExecutionFailedEvent) Reset() {
	*x = ToolExecutionFailedEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionFailedEvent) ProtoMessage() {}

func (x *ToolExecutionFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolExecutionFailedEvent.ProtoReflect.Descriptor instead.
func (*ToolExecutionFailedEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{20}
}

func (x *ToolExecutionFailedEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolExecutionFailedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ToolBatchCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolBatchCompletedEvent) Reset() {
	*x = ToolBatchCompletedEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolBatchCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolBatchCompletedEvent) ProtoMessage() {}

func (x *ToolBatchCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolBatchCompletedEvent.ProtoReflect.Descriptor instead.
func (*ToolBatchCompletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{21}
}

func (x *ToolBatchCompletedEvent) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type RunCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCompletedEvent) Reset() {
	*x = RunCompletedEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCompletedEvent) ProtoMessage() {}

func (x *RunCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCompletedEvent.ProtoReflect.Descriptor instead.
func (*RunCompletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{22}
}

func (x *RunCompletedEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunCompletedEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RunCancelledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCancelledEvent) Reset() {
	*x = RunCancelledEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCancelledEvent) ProtoMessage() {}

func (x *RunCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCancelledEvent.ProtoReflect.Descriptor instead.
func (*RunCancelledEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{23}
}

func (x *RunCancelledEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RunFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFailedEvent) Reset() {
	*x = RunFailedEvent{}
	mi := &file_proto_kontekst_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFailedEvent) ProtoMessage() {}

func (x *RunFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kontekst_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFailedEvent.ProtoReflect.Descriptor instead.
func (*RunFailedEvent) Descriptor() ([]byte, []int) {
	return file_proto_kontekst_proto_rawDescGZIP(), []int{24}
}

func (x *RunFailedEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunFailedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_kontekst_proto protoreflect.FileDescriptor

const file_proto_kontekst_proto_rawDesc = "" +
	"\n" +
	"\x14proto/kontekst.proto\x12\bkontekst\"\x12\n" +
	"\x10GetStatusRequest\"\xde\x02\n" +
	"\x11GetStatusResponse\x12\x12\n" +
	"\x04bind\x18\x01 \x01(\tR\x04bind\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tmodel_dir\x18\x04 \x01(\tR\bmodelDir\x120\n" +
	"\x14llama_server_healthy\x18\x06 \x01(\bR\x12llamaServerHealthy\x120\n" +
	"\x14llama_server_running\x18\a \x01(\bR\x12llamaServerRunning\x12(\n" +
	"\x10llama_server_pid\x18\b \x01(\x05R\x0ellamaServerPid\x12%\n" +
	"\x0euptime_seconds\x18\t \x01(\x03R\ruptimeSeconds\x12,\n" +
	"\x12started_at_rfc3339\x18\n" +
	" \x01(\tR\x10startedAtRfc3339\x12\x19\n" +
	"\bdata_dir\x18\v \x01(\tR\adataDir\"\x11\n" +
	"\x0fShutdownRequest\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xfe\x02\n" +
	"\n" +
	"RunCommand\x121\n" +
	"\x05start\x18\x01 \x01(\v2\x19.kontekst.StartRunCommandH\x00R\x05start\x12A\n" +
	"\fapprove_tool\x18\x02 \x01(\v2\x1c.kontekst.ApproveToolCommandH\x00R\vapproveTool\x128\n" +
	"\tdeny_tool\x18\x03 \x01(\v2\x19.kontekst.DenyToolCommandH\x00R\bdenyTool\x12C\n" +
	"\vapprove_all\x18\x04 \x01(\v2 .kontekst.ApproveAllToolsCommandH\x00R\n" +
	"approveAll\x12:\n" +
	"\bdeny_all\x18\x05 \x01(\v2\x1d.kontekst.DenyAllToolsCommandH\x00R\adenyAll\x124\n" +
	"\x06cancel\x18\x06 \x01(\v2\x1a.kontekst.CancelRunCommandH\x00R\x06cancelB\t\n" +
	"\acommand\"\xb9\x01\n" +
	"\x0fStartRunCommand\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x03 \x01(\tR\tagentName\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12/\n" +
	"\x05skill\x18\x05 \x01(\v2\x19.kontekst.SkillInvocationR\x05skill\"C\n" +
	"\x0fSkillInvocation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"-\n" +
	"\x12ApproveToolCommand\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"B\n" +
	"\x0fDenyToolCommand\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"3\n" +
	"\x16ApproveAllToolsCommand\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"H\n" +
	"\x13DenyAllToolsCommand\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x12\n" +
	"\x10CancelRunCommand\"\xe4\x05\n" +
	"\bRunEvent\x125\n" +
	"\astarted\x18\x01 \x01(\v2\x19.kontekst.RunStartedEventH\x00R\astarted\x121\n" +
	"\x05token\x18\x02 \x01(\v2\x19.kontekst.TokenDeltaEventH\x00R\x05token\x12=\n" +
	"\treasoning\x18\x03 \x01(\v2\x1d.kontekst.ReasoningDeltaEventH\x00R\treasoning\x12I\n" +
	"\x0ebatch_proposed\x18\x04 \x01(\v2 .kontekst.ToolBatchProposedEventH\x00R\rbatchProposed\x12H\n" +
	"\ftool_started\x18\x05 \x01(\v2#.kontekst.ToolExecutionStartedEventH\x00R\vtoolStarted\x12N\n" +
	"\x0etool_completed\x18\x06 \x01(\v2%.kontekst.ToolExecutionCompletedEventH\x00R\rtoolCompleted\x12E\n" +
	"\vtool_failed\x18\a \x01(\v2\".kontekst.ToolExecutionFailedEventH\x00R\n" +
	"toolFailed\x12L\n" +
	"\x0fbatch_completed\x18\b \x01(\v2!.kontekst.ToolBatchCompletedEventH\x00R\x0ebatchCompleted\x12;\n" +
	"\tcompleted\x18\t \x01(\v2\x1b.kontekst.RunCompletedEventH\x00R\tcompleted\x12;\n" +
	"\tcancelled\x18\n" +
	" \x01(\v2\x1b.kontekst.RunCancelledEventH\x00R\tcancelled\x122\n" +
	"\x06failed\x18\v \x01(\v2\x18.kontekst.RunFailedEventH\x00R\x06failedB\a\n" +
	"\x05event\"f\n" +
	"\x0fRunStartedEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x03 \x01(\tR\tagentName\"%\n" +
	"\x0fTokenDeltaEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\")\n" +
	"\x13ReasoningDeltaEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"e\n" +
	"\x16ToolBatchProposedEvent\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x120\n" +
	"\x05calls\x18\x02 \x03(\v2\x1a.kontekst.ProposedToolCallR\x05calls\"\x80\x01\n" +
	"\x10ProposedToolCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\x12\x18\n" +
	"\apreview\x18\x04 \x01(\tR\apreview\"4\n" +
	"\x19ToolExecutionStartedEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"N\n" +
	"\x1bToolExecutionCompletedEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"I\n" +
	"\x18ToolExecutionFailedEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x17ToolBatchCompletedEvent\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"D\n" +
	"\x11RunCompletedEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"*\n" +
	"\x11RunCancelledEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"=\n" +
	"\x0eRunFailedEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2C\n" +
	"\fAgentService\x123\n" +
	"\x03Run\x12\x14.kontekst.RunCommand\x1a\x12.kontekst.RunEvent(\x010\x012\x98\x01\n" +
	"\rDaemonService\x12D\n" +
	"\tGetStatus\x12\x1a.kontekst.GetStatusRequest\x1a\x1b.kontekst.GetStatusResponse\x12A\n" +
	"\bShutdown\x12\x19.kontekst.ShutdownRequest\x1a\x1a.kontekst.ShutdownResponseB1Z/github.com/erg0nix/kontekst/internal/grpc/pb;pbb\x06proto3"

var (
	file_proto_kontekst_proto_rawDescOnce sync.Once
	file_proto_kontekst_proto_rawDescData []byte
)

func file_proto_kontekst_proto_rawDescGZIP() []byte {
	file_proto_kontekst_proto_rawDescOnce.Do(func() {
		file_proto_kontekst_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kontekst_proto_rawDesc), len(file_proto_kontekst_proto_rawDesc)))
	})
	return file_proto_kontekst_proto_rawDescData
}

var file_proto_kontekst_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_kontekst_proto_goTypes = []any{
	(*GetStatusRequest)(nil),            // 0: kontekst.GetStatusRequest
	(*GetStatusResponse)(nil),           // 1: kontekst.GetStatusResponse
	(*ShutdownRequest)(nil),             // 2: kontekst.ShutdownRequest
	(*ShutdownResponse)(nil),            // 3: kontekst.ShutdownResponse
	(*RunCommand)(nil),                  // 4: kontekst.RunCommand
	(*StartRunCommand)(nil),             // 5: kontekst.StartRunCommand
	(*SkillInvocation)(nil),             // 6: kontekst.SkillInvocation
	(*ApproveToolCommand)(nil),          // 7: kontekst.ApproveToolCommand
	(*DenyToolCommand)(nil),             // 8: kontekst.DenyToolCommand
	(*ApproveAllToolsCommand)(nil),      // 9: kontekst.ApproveAllToolsCommand
	(*DenyAllToolsCommand)(nil),         // 10: kontekst.DenyAllToolsCommand
	(*CancelRunCommand)(nil),            // 11: kontekst.CancelRunCommand
	(*RunEvent)(nil),                    // 12: kontekst.RunEvent
	(*RunStartedEvent)(nil),             // 13: kontekst.RunStartedEvent
	(*TokenDeltaEvent)(nil),             // 14: kontekst.TokenDeltaEvent
	(*ReasoningDeltaEvent)(nil),         // 15: kontekst.ReasoningDeltaEvent
	(*ToolBatchProposedEvent)(nil),      // 16: kontekst.ToolBatchProposedEvent
	(*ProposedToolCall)(nil),            // 17: kontekst.ProposedToolCall
	(*ToolExecutionStartedEvent)(nil),   // 18: kontekst.ToolExecutionStartedEvent
	(*ToolExecutionCompletedEvent)(nil), // 19: kontekst.ToolExecutionCompletedEvent
	(*ToolExecutionFailedEvent)(nil),    // 20: kontekst.ToolExecutionFailedEvent
	(*ToolBatchCompletedEvent)(nil),     // 21: kontekst.ToolBatchCompletedEvent
	(*RunCompletedEvent)(nil),           // 22: kontekst.RunCompletedEvent
	(*RunCancelledEvent)(nil),           // 23: kontekst.RunCancelledEvent
	(*RunFailedEvent)(nil),              // 24: kontekst.RunFailedEvent
}
var file_proto_kontekst_proto_depIdxs = []int32{
	5,  // 0: kontekst.RunCommand.start:type_name -> kontekst.StartRunCommand
	7,  // 1: kontekst.RunCommand.approve_tool:type_name -> kontekst.ApproveToolCommand
	8,  // 2: kontekst.RunCommand.deny_tool:type_name -> kontekst.DenyToolCommand
	9,  // 3: kontekst.RunCommand.approve_all:type_name -> kontekst.ApproveAllToolsCommand
	10, // 4: kontekst.RunCommand.deny_all:type_name -> kontekst.DenyAllToolsCommand
	11, // 5: kontekst.RunCommand.cancel:type_name -> kontekst.CancelRunCommand
	6,  // 6: kontekst.StartRunCommand.skill:type_name -> kontekst.SkillInvocation
	13, // 7: kontekst.RunEvent.started:type_name -> kontekst.RunStartedEvent
	14, // 8: kontekst.RunEvent.token:type_name -> kontekst.TokenDeltaEvent
	15, // 9: kontekst.RunEvent.reasoning:type_name -> kontekst.ReasoningDeltaEvent
	16, // 10: kontekst.RunEvent.batch_proposed:type_name -> kontekst.ToolBatchProposedEvent
	18, // 11: kontekst.RunEvent.tool_started:type_name -> kontekst.ToolExecutionStartedEvent
	19, // 12: kontekst.RunEvent.tool_completed:type_name -> kontekst.ToolExecutionCompletedEvent
	20, // 13: kontekst.RunEvent.tool_failed:type_name -> kontekst.ToolExecutionFailedEvent
	21, // 14: kontekst.RunEvent.batch_completed:type_name -> kontekst.ToolBatchCompletedEvent
	22, // 15: kontekst.RunEvent.completed:type_name -> kontekst.RunCompletedEvent
	23, // 16: kontekst.RunEvent.cancelled:type_name -> kontekst.RunCancelledEvent
	24, // 17: kontekst.RunEvent.failed:type_name -> kontekst.RunFailedEvent
	17, // 18: kontekst.ToolBatchProposedEvent.calls:type_name -> kontekst.ProposedToolCall
	4,  // 19: kontekst.AgentService.Run:input_type -> kontekst.RunCommand
	0,  // 20: kontekst.DaemonService.GetStatus:input_type -> kontekst.GetStatusRequest
	2,  // 21: kontekst.DaemonService.Shutdown:input_type -> kontekst.ShutdownRequest
	12, // 22: kontekst.AgentService.Run:output_type -> kontekst.RunEvent
	1,  // 23: kontekst.DaemonService.GetStatus:output_type -> kontekst.GetStatusResponse
	3,  // 24: kontekst.DaemonService.Shutdown:output_type -> kontekst.ShutdownResponse
	22, // [22:25] is the sub-list for method output_type
	19, // [19:22] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_kontekst_proto_init() }
func file_proto_kontekst_proto_init() {
	if File_proto_kontekst_proto != nil {
		return
	}
	file_proto_kontekst_proto_msgTypes[4].OneofWrappers = []any{
		(*RunCommand_Start)(nil),
		(*RunCommand_ApproveTool)(nil),
		(*RunCommand_DenyTool)(nil),
		(*RunCommand_ApproveAll)(nil),
		(*RunCommand_DenyAll)(nil),
		(*RunCommand_Cancel)(nil),
	}
	file_proto_kontekst_proto_msgTypes[12].OneofWrappers = []any{
		(*RunEvent_Started)(nil),
		(*RunEvent_Token)(nil),
		(*RunEvent_Reasoning)(nil),
		(*RunEvent_BatchProposed)(nil),
		(*RunEvent_ToolStarted)(nil),
		(*RunEvent_ToolCompleted)(nil),
		(*RunEvent_ToolFailed)(nil),
		(*RunEvent_BatchCompleted)(nil),
		(*RunEvent_Completed)(nil),
		(*RunEvent_Cancelled)(nil),
		(*RunEvent_Failed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kontekst_proto_rawDesc), len(file_proto_kontekst_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_kontekst_proto_goTypes,
		DependencyIndexes: file_proto_kontekst_proto_depIdxs,
		MessageInfos:      file_proto_kontekst_proto_msgTypes,
	}.Build()
	File_proto_kontekst_proto = out.File
	file_proto_kontekst_proto_goTypes = nil
	file_proto_kontekst_proto_depIdxs = nil
}
